eclipse-edc/FederatedCatalog

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pull-request.yaml
.gitignore
CODEOWNERS
README.md
docs/developer/decision-records/README.md
docs/templates/README.md
docs/templates/decision-record.md
docs/templates/puml-colors.txt

- Adds inital files (`README`, `.gitignore`, etc.)
- Adds PR validation (enforce conventional commits on main)
- Adds issue templates
- Removes duplicated contribution files and references the connector repo
- Adds toc of decision records (list will be shown via GitHub pages)
Align with main repo, prepare for external documentation framework, improve community contributions
--

chore: align workflows, guidelines and documentation with connector repo

---

CODEOWNERS
NOTICE.md

Perform the third-party scanning and add the content to `NOTICE.md`
E-F compliance
.
.

chore: add third-party content to notice file

---

CODEOWNERS
NOTICE.md
launchers/Dockerfile
launchers/build.gradle.kts
settings.gradle.kts

Adds a very basic launcher to the FCC
Will be used in a system test, or just as sample.
- uses all in-mem impls
- system test will follow in another PR
Closes https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/995

feat: add standalone launcher

---

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java

fix unit tests
ci
did some cleanup
Closes #57

build: fix unit tests, cleanup

---

system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java

fix: compilation

---

system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/ManagementApiClient.java
system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java

Fix compilation issues
ci
refactored a test a little, and make it use the new /v3/assets endpoint

fix: compilation issue

---

DEPENDENCIES

fix: update dependencies

---

DEPENDENCIES
build.gradle.kts
extensions/api/federated-catalog-api/build.gradle.kts
gradle/libs.versions.toml

- fix: compile and test errors
- removed obsolete module
Fixes some compile and nasty test errors
keep in step with EDC main

fix: compile errors and tests

---

DEPENDENCIES
gradle/libs.versions.toml

Solves build errors that were introduced by recent upstream developments

fix(test): resolves build errors

---

.github/workflows/scan-pull-request.yaml
DEPENDENCIES
gradle/wrapper/gradle-wrapper.properties

build: bump gradle wrapper to 8.5

---

.github/workflows/publish-openapi-ui.yml
.github/workflows/release-fcc.yml
DEPENDENCIES

Add workflow to publish openapi UI.
API documentation.

docs: publish openapi ui

---

DEPENDENCIES
extensions/api/federated-catalog-api/build.gradle.kts
extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java
system-tests/component-tests/build.gradle.kts
system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
system-tests/end2end-test/e2e-junit-runner/build.gradle.kts

chore: recent EDC updates

---

.github/workflows/publish-autodoc.yml
.github/workflows/release-fcc.yml
DEPENDENCIES

Publish autodoc and openapi.
Documentation.

docs: workflows for openapi and autodoc publication

---

DEPENDENCIES
system-tests/component-tests/build.gradle.kts
system-tests/end2end-test/catalog-runtime/build.gradle.kts
system-tests/end2end-test/connector-runtime/build.gradle.kts

Adds necessary dependencies to runtime build files.

chore: add necessary dependencies to build files

---

DEPENDENCIES
extensions/api/federated-catalog-api/build.gradle.kts
gradle/libs.versions.toml
system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java

fix: fix compile after DSP package refactoring

---

DEPENDENCIES
core/federated-catalog-core/build.gradle.kts
gradle/libs.versions.toml
system-tests/end2end-test/catalog-runtime/build.gradle.kts

fix(dependency): update more dependencies

---

DEPENDENCIES
core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java
gradle/libs.versions.toml
system-tests/end2end-test/e2e-junit-runner/build.gradle.kts

fix(deps): add JSR310 dependency

---

README.md
docs/developer/architecture/federated-catalog-apis.md
docs/developer/architecture/federated-catalog.architecture.md
extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/model/ExecutionPlan.java
spi/federated-catalog-spi/README.md

Adds and updates documentation about the FederatedCatalog, its architecture and APIs
Closes #197

docs: add and improve documentation

---

DEPENDENCIES
core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
core/crawler-core/src/test/java/org/eclipse/edc/catalog/cache/ExecutionManagerTest.java

chore: improve some logging

---

DEPENDENCIES
core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java

fix(test): data services are now never null

---

DEPENDENCIES
README.md

updates the readme
Closes #222

docs: fix README with proper paths and commands

---

DEPENDENCIES
extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtension.java

fix datasource name typo
bugfix

chore: fix datasource name typo

---

DEPENDENCIES
core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java

Fix compilation on main branch

build: fix compilation

---

DEPENDENCIES
gradle/libs.versions.toml
system-tests/end2end-test/connector-runtime/build.gradle.kts

ci: fix tests on main by removing unneeded dependency

---

system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/instrumentation/MockInjectionExtension.java

fix: compile error after recent EDC updates

---

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformer.java
core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java
extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheTest.java
extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryTest.java
system-tests/component-tests/src/test/resources/catalog_of_catalogs.json

fix after subcatalog serialization changes
bug fix

chore: fix after subcatalog serialization changes

---

extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtension.java
system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java

build: fix tests

---

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java

Set default initial delay to 0.
random one does not make sense
_Please @-mention the committer that will sponsor your feature_.
Closes #320 

feat: set default initial delay to 0

---

.github/dependabot.yml
launchers/catalog-dcp/Dockerfile
launchers/catalog-mocked/Dockerfile

as done in the identityhub
_Please @-mention the committer that will sponsor your feature_.

build: fix docker launchers

---

core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
core/federated-catalog-core-08/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
core/federated-catalog-core-2025/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/crawler/RecurringExecutionPlan.java
core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/crawler/RecurringExecutionPlanTest.java
spi/crawler-spi/src/main/java/org/eclipse/edc/crawler/spi/model/ExecutionPlan.java

Updates  `Fraunhofer-Gesellschaft` to `Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.` in all affected license headers.
_Please @-mention the committer that will sponsor your feature_.

chore: update Fraunhofer license headers
