.github/workflows/verify.yaml, core/federated-catalog/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java, core/federated-catalog/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java, core/federated-catalog/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java, system-tests/end2end-test/e2e-junit-runner/build.gradle.kts, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Adds the `workflow_dispatch` event trigger to `verify.yaml`
to be able to trigger the build from external systems through the Github API (e.g. Jenkins).
Closes https://github.com/eclipse-edc/Connector/issues/2281
- fixed some NPE's in the tests, that were introduced by recent changes in the connector.
=> feat(build): add workflow_dispatch event trigger

gradle/wrapper/gradle-wrapper.properties, launchers/build.gradle.kts, system-tests/end2end-test/catalog-runtime/build.gradle.kts, system-tests/end2end-test/connector-runtime/build.gradle.kts, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Upgrades to Gradle v 8.0
To keep in step with current developments, avoid technical debt.
.
=> chore: upgrade to Gradle 8.0

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedRequestFetcher.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java, extensions/store/fcc-node-directory-cosmos/src/main/java/org/eclipse/edc/catalog/node/directory/azure/CosmosFederatedCacheNodeDirectory.java, extensions/store/fcc-node-directory-cosmos/src/test/java/org/eclipse/edc/catalog/node/directory/azure/CosmosFederatedCacheNodeDirectoryTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/instrumentation/MockInjectionExtension.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/matchers/CatalogRequestMatcher.java, system-tests/end2end-test/catalog-runtime/src/main/java/org/eclipse/edc/catalog/node/directory/filesystem/CatalogExtension.java, system-tests/end2end-test/catalog-runtime/src/main/java/org/eclipse/edc/catalog/node/directory/filesystem/FileBasedNodeDirectory.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/ManagementApiClient.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Adapts the code to fit to the latest changes in the upstream:
- update usage of the `CosmosDbApi`
- remove usages of `MessageContext`
fix compiler errors
.
Closes #
=> chore: adapt code to fit to the latest connector upstream

build.gradle.kts, core/federated-catalog-core/build.gradle.kts, extensions/api/federated-catalog-api/build.gradle.kts, extensions/store/fcc-node-directory-cosmos/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, launchers/build.gradle.kts, settings.gradle.kts, spi/federated-catalog-spi/build.gradle.kts, system-tests/component-tests/build.gradle.kts, system-tests/end2end-test/catalog-runtime/build.gradle.kts, system-tests/end2end-test/connector-runtime/build.gradle.kts, system-tests/end2end-test/docker-compose.yml, system-tests/end2end-test/e2e-junit-runner/build.gradle.kts
- Move the version catalog to the default `gradle/libs.versions.toml`
- Create publication of the catalog called `federated-catalog-versions`
- import the `GradlePlugins` catalog as `root` (no better terms came to mind, `edc` would be too redundant, `super` cannot be used...)
version catalog refactoring
- ~~some versions as `mockito`, `jackson`... are needed because `DefaultDependencyConvention` (in `GradlePlugins`) requires them, I'd say that this need to change (will be fixed by https://github.com/eclipse-edc/GradlePlugins/pull/127)~~ fix merged
Closes #90
=> build: publish version catalog

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedRequestFetcher.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspNodeQueryAdapter.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/IdsMultipartNodeQueryAdapter.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java, core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
Adds a query adapter for the DSP protocol.
Compliance with the new DSP protocol
- The `FederatedCacheNode.targetUrl` **MUST** contain the full path of the DSP endpoint
- The `FederatedCacheNode.supportedProtocols` **MUST ONLY** contain `"dataspace-protocol-http"`, please remove the old `ids-multipart`
=> feat(protocol): add query adapter for the new DSP

.github/actions/bump-version/action.yml, .github/workflows/release-fcc.yml, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Adds a job to automatically bump the version after a GH release
updated the version automatically
- fixed a compile error due to the renaming of a constant
=> build: add action to bump the snapshot version

.github/actions/bump-version/action.yml, core/federated-catalog-core/build.gradle.kts, docs/legal/generateThirdPartyReport.sh, gradle.properties, gradle/libs.versions.toml, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Update snapshot version to `0.1.0-SNAPSHOT`
Our next release version will be `0.1.0`, thus the next snapshot will be `0.1.1-SNAPSHOT` and the automatic version bump mechanism currently only bumps the `patch` version.
- depends on https://github.com/eclipse-edc/GradlePlugins/pull/162
- depends on https://github.com/eclipse-edc/Connector/pull/3108
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)._
=> chore: update snapshot version to 0.1.0-SNAPSHOT

extensions/store/fcc-node-directory-cosmos/src/main/java/org/eclipse/edc/catalog/node/directory/azure/CosmosFederatedCacheNodeDirectoryExtension.java, spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CatalogConstants.java
Use EDC namespace for `originator` property
Use proper namespace.
=> fix: Use EDC namespace for originator property

.github/workflows/verify.yaml, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java
Expanding a JSON structure that does not contain `@context` fails, so the expansion step was removed.
runtime error 
=> fix: runtime error due to faulty model transformation

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedRequestFetcher.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedRequestFetcherTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java
Uses `RemoteMessageDispatcher#dispatch` now, as the `send()` method was deprecated. Fixes tests.
Component tests were broken, and the `send()` method was deprecated
.
=> fix: use the new dispatcher.dispatch method

core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java, extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java, extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiController.java, extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogCacheQueryApiExtension.java, extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/ManagementApiClient.java
Upgrades the Federated Catalog's Query API to JSON-LD, to be consistent with the rest of EDC's APIs.
All our APIs should be JSON-LD-aware. In addition, this fixes a weird bug, where the `Dataset#offers` array was returned empty - most of the time. That's why it's a `fix/` PR.
=> fix: upgrade catalog-api to JSON-LD

DEPENDENCIES, gradle/libs.versions.toml, system-tests/end2end-test/connector-runtime/build.gradle.kts
Fixes the failing test by adding a DataFlowController to the connector runtime.
Tests were failing, because without a DataFlowController there are no Distributions.
=> fix(test): add a DataFlowController to test runtime

DEPENDENCIES, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
=> fix: unit tests

extensions/api/federated-catalog-api/build.gradle.kts, gradle/libs.versions.toml
=> fix: use explicit module dependency

DEPENDENCIES, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/TestFunctions.java
Uses the correct data address src type `test-src-type`, otherwise no distribution was created causing the test to fail.
failing test
=> fix: use correct DataAddress type (src) in E2E test

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/store/InMemoryFederatedCacheStore.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java
This PR adapts to the latest changes in upstream EDC, most notably w.r.t. the
`CriterionOperatorRegistry` and the `PropertyLookup` functions.
Compile errors
=> chore: incorporate latest changes of EDC

DEPENDENCIES, core/crawler-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java, core/federated-catalog-core/build.gradle.kts, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/BatchedCatalogRequestFetcher.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformer.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformer.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDistributionTransformer.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/BatchedCatalogRequestFetcherTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToCatalogTransformerTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformerTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformerTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDistributionTransformerTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/TestInput.java, core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java, extensions/api/federated-catalog-api/build.gradle.kts, extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java, gradle/libs.versions.toml, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java, system-tests/end2end-test/e2e-junit-runner/build.gradle.kts, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
This PR adapts the FCC code base to the latest changes in upstream EDC, most notably:
- restores the `JsonObjectTo...` transformers, that were removed from upstream code in [this commit](https://github.com/eclipse-edc/Connector/commit/2857d375a5d158f8de8fe5cafa9a19d6c619dd33)
- registers the transformers
- adapts package names / imports for the existing catalog transformers
- adds the `participantId` to catalogs in tests
keep in-step with upstream
_Please be sure to take a look at the [contributing …
=> chore: adapt code to latest EDC

DEPENDENCIES, extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApi.java
Fix swagger API:
- adds `info` section
- remove `50x` status code which is not supported
Documentation.
=> docs: fix catalog swagger API

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java, spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CacheSettings.java
Moves all `@Settings` annotated fields into extension classes, lest autodoc complains
=> fix: move settings into extensions

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformerTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDistributionTransformerTest.java
Fixes a compile error after an  upstream refactoring of the `DataService` class.
=> fix: compile error after DataService refactoring

DEPENDENCIES, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
Properly configures the `control` context for the test runtime
A recent refactoring upstream requires this
=> fix: configure control path/port in test

.github/workflows/verify.yaml, DEPENDENCIES, launchers/build.gradle.kts
This PR fixes the broken launcher, that missed some dependencies. I also added a test to verify the launcher can boot up correctly.
After the upstream package refactoring a while ago, some runtime dependencies were missing
Closes #193
=> fix(build): repair broken launcher

.github/workflows/verify.yaml, DEPENDENCIES, extensions/api/federated-catalog-api/build.gradle.kts, extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogCacheQueryApiExtension.java, extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java, gradle/libs.versions.toml, spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/FccApiContexts.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/TestFunctions.java, system-tests/end2end-test/connector-runtime/build.gradle.kts, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/CatalogApiClient.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
This PR uses a constant for the catalog cache api context instead of the now-removed `ManagementApiConfiguration`.
it was removed.
- **IMPORTANT: this moves the configuration to `web.http.catalog.[port|path]`, which is a breaking change!!**
=> fix: use constant as API context

DEPENDENCIES, gradle/libs.versions.toml, launchers/build.gradle.kts, system-tests/component-tests/build.gradle.kts, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/CatalogRuntimeComponentTest.java, system-tests/component-tests/src/test/java/org/eclipse/edc/catalog/instrumentation/MockInjectionExtension.java, system-tests/end2end-test/catalog-runtime/build.gradle.kts, system-tests/end2end-test/connector-runtime/src/main/java/org/eclipse/edc/federatedcatalog/end2end/DataplaneInstanceRegistrationExtension.java, system-tests/end2end-test/e2e-junit-runner/src/test/java/org/eclipse/edc/end2end/FederatedCatalogTest.java
=> fix: adopt new test runtime model

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java, extensions/api/federated-catalog-api/build.gradle.kts, extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiControllerTest.java, gradle/libs.versions.toml, system-tests/end2end-test/connector-runtime/src/main/java/org/eclipse/edc/federatedcatalog/end2end/DataplaneInstanceRegistrationExtension.java
Adopts the new test runtime model of upstream EDC
Avoid technical debt
=> chore(test): adopt EDC test runtime model

core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformer.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/transform/JsonObjectToDatasetTransformerTest.java
the list of `distribution` objects in the `DataSet` class can be null. For the purposes of the FC we always should initialize the list, even if no distribution is there.
I don't know if this is mandated by the DCAT spec or not, but in FC it makes things easier if it's not `null`.
ease of use when processing catalogs, that contain datasets without distributions.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette …
=> fix(transform): make sure Distributions are never null

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogDefaultServicesExtension.java
declares the `ExecutionPlan` provider as `default` to make it overridable
pluggability
=> chore: make ExecutionPlan pluggable

core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtensionTest.java
adds a flag to disable the Federated Catalog Crawlers globally
in some circumstances it might be useful to disable the crawlers, for example when proper configuration is missing.
=> feat: add global disable flag for Crawlers

DEPENDENCIES, core/federated-catalog-core/build.gradle.kts, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/defaults/store/InMemoryFederatedCatalogCacheTest.java, extensions/store/sql/federated-catalog-cache-sql/build.gradle.kts, extensions/store/sql/federated-catalog-cache-sql/docs/schema.sql, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/BaseSqlDialectStatements.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/FederatedCatalogCacheStatements.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCache.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtension.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/FederatedCatalogMapping.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/PostgresDialectStatements.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/PrefixedJsonFieldTranslator.java, extensions/store/sql/federated-catalog-cache-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtensionTest.java, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheTest.java, gradle/libs.versions.toml, settings.gradle.kts, spi/federated-catalog-spi/build.gradle.kts, spi/federated-catalog-spi/src/testFixtures/java/org/eclipse/edc/catalog/spi/testfixtures/FederatedCatalogCacheTestBase.java
=> feat: sql federated catalog cache

DEPENDENCIES, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCache.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtension.java, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtensionTest.java, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheTest.java, spi/federated-catalog-spi/src/testFixtures/java/org/eclipse/edc/catalog/spi/testfixtures/FederatedCatalogCacheTestBase.java
Fixes JSON serde for Catalog when datasets contains an embedded catalog by
registering `Catalog` and `Dataset` types in the `TypeManager` where now `Dataset` is polymorphic https://github.com/eclipse-edc/Connector/pull/4362 
bugfix
=> fix: add nested catalog test + types registration

extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtension.java, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlFederatedCatalogCacheExtensionTest.java
Separate datasource from sql store configuration
Closes #237 
=> refactor: separate sql stores from datasources

DEPENDENCIES, core/federated-catalog-core/build.gradle.kts, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/directory/InMemoryNodeDirectory.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/directory/InMemoryNodeDirectoryTest.java, extensions/store/sql/target-node-directory-sql/build.gradle.kts, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/BaseSqlDialectStatements.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectory.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryExtension.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/TargetNodeStatements.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/PostgresDialectStatements.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/store/sql/schema/postgres/TargetNodeMapping.java, extensions/store/sql/target-node-directory-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/store/sql/target-node-directory-sql/src/main/resources/target-node-directory-schema.sql, extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryExtensionTest.java, extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/store/sql/SqlTargetNodeDirectoryTest.java, settings.gradle.kts, spi/crawler-spi/build.gradle.kts, spi/crawler-spi/src/testFixtures/java/org/eclipse/edc/catalog/spi/testfixtures/TargetNodeDirectoryTestBase.java
SQL implementation of `TargetNodeDirectory`.
Persistent implementation of `TargetNodeDirectory`.
Closes #240 
=> feat: SQL implementation of `TargetNodeDirectory`

DEPENDENCIES, extensions/api/federated-catalog-api/src/main/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtension.java, extensions/api/federated-catalog-api/src/test/java/org/eclipse/edc/catalog/api/query/FederatedCatalogApiExtensionTest.java
adds missing namespace in  `CATALOG_QUERY_API` scope after [this](https://github.com/eclipse-edc/Connector/pull/4470) refactor.
=> chore: adds missing namespace in catalog query scope

DEPENDENCIES, core/federated-catalog-core/build.gradle.kts, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestAction.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestActionTest.java, core/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/query/PagingCatalogFetcherTest.java, core/federated-catalog-core/src/testFixtures/java/org/eclipse/edc/catalog/test/TestUtil.java
Fixes a potential exception in the `DspCatalogRequestAction` that parses nested catalogs.
avoids a potential NPE when a root catalog contains only a nested catalog but no other datasets
- moves some test methods into the `testFixtures` package
=> fix: avoid exception DSP Request Action

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheExtension.java
It has changed after the introduction of multi protocol version transfomers [here](https://github.com/eclipse-edc/Connector/pull/4514).
For now it hard code the v0.8 as it was before. We should plan to support multi protocol version also in FC
bug fix
=> fix: change transform context from dsp-api to dsp-api:v0.8

DEPENDENCIES, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/cache/query/DspCatalogRequestAction.java, core/federated-catalog-core/src/main/java/org/eclipse/edc/catalog/transform/JsonObjectToDataServiceTransformer.java, system-tests/component-tests/src/test/resources/catalog.json, system-tests/component-tests/src/test/resources/catalog_of_catalogs.json
=> fix: use correct dcat:endpointURL spelling

dist/bom/federatedcatalog-dcp-bom/build.gradle.kts
enables the publication for the FC DCP BOM
it wasn't enabled before.
=> fix: enable publishing the DCP BOM

.github/workflows/verify.yaml, settings.gradle.kts, system-tests/bom-tests/build.gradle.kts, system-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
use E2E tests for BOM smoke tests
more mockable, more stable test methodology
=> feat(ci): use E2E tests for BOM Smoke tests

extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/BaseSqlDialectStatements.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/FederatedCatalogCacheStatements.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/SqlFederatedCatalogCache.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/SqlFederatedCatalogCacheExtension.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/schema/postgres/FederatedCatalogMapping.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/schema/postgres/PostgresDialectStatements.java, extensions/store/sql/federated-catalog-cache-sql/src/main/java/org/eclipse/edc/catalog/cache/sql/schema/postgres/PrefixedJsonFieldTranslator.java, extensions/store/sql/federated-catalog-cache-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/cache/sql/SqlFederatedCatalogCacheExtensionTest.java, extensions/store/sql/federated-catalog-cache-sql/src/test/java/org/eclipse/edc/catalog/cache/sql/SqlFederatedCatalogCacheTest.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/directory/sql/BaseSqlDialectStatements.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/directory/sql/SqlTargetNodeDirectory.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/directory/sql/SqlTargetNodeDirectoryExtension.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/directory/sql/TargetNodeStatements.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/directory/sql/schema/postgres/PostgresDialectStatements.java, extensions/store/sql/target-node-directory-sql/src/main/java/org/eclipse/edc/catalog/directory/sql/schema/postgres/TargetNodeMapping.java, extensions/store/sql/target-node-directory-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/directory/sql/SqlTargetNodeDirectoryExtensionTest.java, extensions/store/sql/target-node-directory-sql/src/test/java/org/eclipse/edc/catalog/directory/sql/SqlTargetNodeDirectoryTest.java
Renames packages in:
module `federated-catalog-cache-sql`: `org.eclipse.edc.catalog.store.sql.*` to `org.eclipse.edc.catalog.cache.sql.*`
module `target-node-directory-sql`: `org.eclipse.edc.catalog.store.sql.*` to  `org.eclipse.edc.catalog.directory.sql.*`
The duplicate package names could cause a conflict in class resolution. Especially because `PostgresDialectStatements` ends up having the same FQCN in both modules.
@ndr-brt 
Closes #286 
=> fix: sql-duplicate-class-fqcn

.github/workflows/verify.yaml, core/crawler-core/src/main/java/org/eclipse/edc/catalog/cache/ExecutionManager.java
Remove logs on every plan iteration.
improve debug experience
- extracted a `runTask`, just for the sake of duplication removal
- re-enabled Postgresql tests
_Please @-mention the committer that will sponsor your feature_.
Closes #308 
Closes #313 
=> refactor: reduce logs

core/federated-catalog-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
Removes the invalid service definition `org.eclipse.edc.catalog.cache.FederatedCatalogCacheExtension` from 
`META-INF/services/org.eclipse.edc.spi.system.ServiceExtension` in the `federated-catalog-core` module.  
The referenced class is not part of the `federated-catalog-core` module but only exists in 
`federated-catalog-core-2025` and the deprecated `federated-catalog-core-08` modules.  
Keeping the service definition in `federated-catalog-core` caused a `ServiceConfigurationError` when neither of those 
modules are included at runtime.  
@ndr-brt 
Closes #342
=> fix: remove invalid service definition from module fc-core
